### ISSUE TITLE
An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by ryanshrott** [deta/docs#591]
I get this error periodically in some of my apps. Is it a Deta issue or an issue with my server? Not sure. Any idea what the cause could be?

2022-11-13 12:03:24,056 - root - ERROR - Traceback (most recent call last):
  File "C:\Users\Ryan\PycharmProjects\smartbids\scripts\generate_all_data.py", line 45, in <module>
    save_file_to_cloud_pickle(X, 'engineeredX.pickle')
  File "C:\Users\Ryan\PycharmProjects\smartbids\ml\utils.py", line 78, in save_file_to_cloud_pickle
    drive.put(file_name, pickled_data)
  File "C:\Users\Ryan\anaconda3\lib\site-packages\deta\drive.py", line 195, in put
    raise e
  File "C:\Users\Ryan\anaconda3\lib\site-packages\deta\drive.py", line 188, in put
    self._upload_part(name, chunk, upload_id, part, content_type)
  File "C:\Users\Ryan\anaconda3\lib\site-packages\deta\drive.py", line 137, in _upload_part
    self._request(
  File "C:\Users\Ryan\anaconda3\lib\site-packages\deta\service.py", line 74, in _request
    res = self._send_request_with_retry(method, url, headers, body)
  File "C:\Users\Ryan\anaconda3\lib\site-packages\deta\service.py", line 114, in _send_request_with_retry
    self.client.request(
  File "C:\Users\Ryan\anaconda3\lib\http\client.py", line 1279, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\Ryan\anaconda3\lib\http\client.py", line 1325, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\Ryan\anaconda3\lib\http\client.py", line 1274, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Ryan\anaconda3\lib\http\client.py", line 1034, in _send_output
    self.send(msg)
  File "C:\Users\Ryan\anaconda3\lib\http\client.py", line 974, in send
    self.connect()
  File "C:\Users\Ryan\anaconda3\lib\http\client.py", line 1448, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "C:\Users\Ryan\anaconda3\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\Ryan\anaconda3\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\Ryan\anaconda3\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

**Comment by el-garro** [comment]
Can you provide more context to the problem? Also, there's a timeout of 10 seconds, you can't maintain a connection for more than that

**Comment by lemonyte** [comment]
This issue should be in [deta/deta-python](https://github.com/deta/deta-python).
