### ISSUE TITLE
Cannot Run Node JS Anymore!

### ISSUE THREAD

**Issue by sancho1952007** [deta/docs#646]
### Discussed in https://github.com/orgs/deta/discussions/645

<div type='discussions-op-text'>

<sup>Originally posted by **sancho1952007** December 13, 2022</sup>
My Python Code Works Fine But The Node Doesn't Work At All!
Error:
```
Error: Unsupported framework
    at getFramework (/opt/nodejs/node_modules/serverless-http/lib/framework/get-framework.js:63:9)
    at module.exports (/opt/nodejs/node_modules/serverless-http/serverless-http.js:14:21)
    at Object.handleCustom (/opt/nodejs/node_modules/detalib/deta/internal/handlers.js:20:19)
    at handler (/opt/nodejs/node_modules/detalib/deta/lib/handler.js:13:46)
    at Object.handler (/opt/nodejs/node_modules/detalib/deta/internal/debug/debugger.js:170:30)
    at Runtime.module.exports.handler (/var/task/_entry.js:11:18)
    at Runtime.handleOnceNonStreaming (/var/runtime/Runtime.js:74:25)
```
</div>

**Comment by lemonyte** [comment]
Resolved in #645.
